services:
  - type: web
    name: nepali-calendar-dashboard-backend
    env: node
    region: oregon
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 18.18.0
    healthCheckPath: /
    autoDeploy: true
    plan: free
